# Generated by Django 4.2.11 on 2024-05-07 07:51

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commodity',
            fields=[
                ('cmd_id', models.AutoField(primary_key=True, serialize=False)),
                ('cmd_name', models.CharField(max_length=255, unique=True)),
                ('cmd_code', models.CharField(max_length=10, unique=True)),
                ('cmd_desc', models.TextField()),
                ('cmd_unit', models.CharField(max_length=50)),
                ('cmd_weight', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('cmd_created_time', models.DateTimeField(auto_now_add=True)),
                ('cmd_updated_time', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'commodity',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('country_id', models.AutoField(primary_key=True, serialize=False)),
                ('country_name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'country',
            },
        ),
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('entity_id', models.AutoField(primary_key=True, serialize=False)),
                ('entity_name', models.CharField(max_length=255, unique=True)),
                ('entity_code', models.CharField(max_length=10, unique=True)),
                ('entity_desc', models.TextField()),
                ('entity_remarks', models.TextField()),
            ],
            options={
                'db_table': 'entity',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('group_id', models.AutoField(primary_key=True, serialize=False)),
                ('group_name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'group',
            },
        ),
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('lab_id', models.AutoField(primary_key=True, serialize=False)),
                ('lab_name', models.CharField(max_length=255, unique=True)),
                ('lab_code', models.CharField(max_length=10, unique=True)),
                ('lab_state_code', models.CharField(max_length=10, unique=True)),
                ('lab_location', models.CharField(max_length=255)),
                ('lab_contact', models.CharField(max_length=10, unique=True, validators=[django.core.validators.MinLengthValidator(10), django.core.validators.MaxLengthValidator(10)])),
                ('lab_address', models.TextField()),
                ('lab_email', models.EmailField(max_length=254, unique=True)),
                ('lab_post_code', models.CharField(max_length=255)),
                ('lab_created_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('lab_updated_time', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'lab',
            },
        ),
        migrations.CreateModel(
            name='Mode',
            fields=[
                ('mode_id', models.AutoField(primary_key=True, serialize=False)),
                ('mode_name', models.CharField(max_length=255, unique=True)),
                ('mode_code', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'mode',
                'ordering': ['mode_id'],
            },
        ),
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('param_id', models.AutoField(primary_key=True, serialize=False)),
                ('param_name', models.CharField(max_length=255, unique=True)),
                ('param_desc', models.TextField()),
                ('param_created_time', models.DateTimeField(auto_now_add=True)),
                ('param_updated_time', models.DateTimeField(auto_now=True, null=True)),
                ('param_cmd_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_api.commodity')),
            ],
            options={
                'db_table': 'parameter',
            },
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('role_id', models.AutoField(primary_key=True, serialize=False)),
                ('role_name', models.CharField(max_length=25, unique=True)),
                ('role_desc', models.TextField()),
            ],
            options={
                'db_table': 'roles',
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('state_id', models.AutoField(primary_key=True, serialize=False)),
                ('state_name', models.CharField(max_length=255, unique=True)),
                ('state_code', models.CharField(max_length=10, unique=True)),
                ('state_country_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_api.country')),
            ],
            options={
                'db_table': 'state',
            },
        ),
        migrations.CreateModel(
            name='Standard',
            fields=[
                ('std_id', models.AutoField(primary_key=True, serialize=False)),
                ('std_name', models.CharField(max_length=255, unique=True)),
                ('std_desc', models.TextField()),
                ('std_created_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('std_updated_time', models.DateTimeField(auto_now=True, null=True)),
                ('std_parameter_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_api.parameter')),
            ],
            options={
                'db_table': 'standard',
            },
        ),
        migrations.CreateModel(
            name='EntityRolesRights',
            fields=[
                ('ent_rnr_id', models.AutoField(primary_key=True, serialize=False)),
                ('ent_rnr_role_code', models.CharField(max_length=10, unique=True)),
                ('ent_rnr_entity_code', models.CharField(max_length=10, unique=True)),
                ('ent_rnr_read', models.BooleanField(default=False)),
                ('ent_rnr_write', models.BooleanField(default=False)),
                ('ent_rnr_update', models.BooleanField(default=False)),
                ('ent_rnr_delete', models.BooleanField(default=False)),
                ('ent_rnr_list', models.BooleanField(default=False)),
                ('ent_rnr_approve', models.BooleanField(default=False)),
                ('ent_rnr_cancel', models.BooleanField(default=False)),
                ('ent_rnr_signature', models.BooleanField(default=False)),
                ('ent_rnr_entity_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_api.entity')),
                ('ent_rnr_role_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_api.roles')),
            ],
            options={
                'db_table': 'entity_roles_rights',
            },
        ),
        migrations.CreateModel(
            name='EntityHistory',
            fields=[
                ('eh_id', models.AutoField(primary_key=True, serialize=False)),
                ('eh_operation', models.CharField(max_length=255)),
                ('eh_empid', models.IntegerField()),
                ('eh_operationdate', models.DateTimeField()),
                ('eh_recordid', models.IntegerField()),
                ('status', models.CharField(blank=True, max_length=255)),
                ('eh_enid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_api.entity')),
            ],
            options={
                'db_table': 'entity_history',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('cmp_id', models.AutoField(primary_key=True, serialize=False)),
                ('cmp_name', models.CharField(max_length=255, unique=True)),
                ('cmp_address', models.TextField()),
                ('cmp_code', models.CharField(max_length=10, unique=True)),
                ('cmp_email', models.EmailField(max_length=254, unique=True)),
                ('cmp_phoneno', models.CharField(max_length=10, unique=True, validators=[django.core.validators.MinLengthValidator(10), django.core.validators.MaxLengthValidator(10)])),
                ('cmp_pan_no', models.CharField(max_length=255, unique=True)),
                ('cmp_cin_no', models.CharField(max_length=255, unique=True)),
                ('cmp_gst_no', models.CharField(max_length=255, unique=True)),
                ('cmp_iec_no', models.CharField(max_length=255, unique=True)),
                ('cmp_created_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('cmp_updated_time', models.DateTimeField(auto_now=True, null=True)),
                ('cmp_country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_api.country')),
                ('cmp_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_api.state')),
            ],
            options={
                'db_table': 'company',
            },
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('br_id', models.AutoField(primary_key=True, serialize=False)),
                ('br_name', models.CharField(max_length=255, unique=True)),
                ('br_phoneno', models.CharField(max_length=10, unique=True, validators=[django.core.validators.MinLengthValidator(10), django.core.validators.MaxLengthValidator(10)])),
                ('br_code', models.CharField(max_length=10, unique=True)),
                ('br_email', models.EmailField(max_length=254, unique=True)),
                ('br_address', models.TextField()),
                ('br_location', models.CharField(max_length=255)),
                ('br_postal_code', models.CharField(max_length=255)),
                ('br_created_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('br_updated_time', models.DateTimeField(auto_now=True, null=True)),
                ('br_comp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_api.company')),
            ],
            options={
                'db_table': 'branch',
            },
        ),
    ]
