# Generated by Django 4.2.11 on 2024-05-07 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantMaster',
            fields=[
                ('tenant_id', models.AutoField(primary_key=True, serialize=False)),
                ('tenant_code', models.CharField(max_length=10, unique=True)),
                ('tenant_name', models.CharField(max_length=255, unique=True)),
                ('tenant_url', models.CharField(max_length=255)),
                ('tenant_db_string', models.CharField(max_length=255)),
                ('tenant_db_server', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'tenant_master',
            },
        ),
        migrations.RenameField(
            model_name='commodity',
            old_name='cmd_code',
            new_name='tenant_code',
        ),
        migrations.RemoveField(
            model_name='parameter',
            name='param_cmd_id',
        ),
        migrations.RemoveField(
            model_name='standard',
            name='std_parameter_id',
        ),
        migrations.AddField(
            model_name='commodity',
            name='cmd_created_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='commodity',
            name='cmd_updated_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='parameter',
            name='param_created_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='parameter',
            name='param_unit',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parameter',
            name='param_unitsymbol',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parameter',
            name='param_updated_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='parameter',
            name='tenant_code',
            field=models.CharField(default=1, max_length=10, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='standard',
            name='std_created_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='standard',
            name='std_updated_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='standard',
            name='tenant_code',
            field=models.CharField(default=1, max_length=10, unique=True),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='CommodityGroup',
            fields=[
                ('cmd_group_id', models.AutoField(primary_key=True, serialize=False)),
                ('tenant_code', models.CharField(max_length=10)),
                ('cmd_discipline_name', models.CharField(max_length=255)),
                ('cmd_group_name', models.CharField(max_length=255)),
                ('fk_tenant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_api.tenantmaster')),
            ],
            options={
                'db_table': 'commodity_group',
            },
        ),
        migrations.AddField(
            model_name='commodity',
            name='fk_tenant_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='master_api.tenantmaster'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parameter',
            name='fk_tenant_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='master_api.tenantmaster'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='standard',
            name='fk_tenant_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='master_api.tenantmaster'),
            preserve_default=False,
        ),
    ]
