# Generated by Django 4.2.11 on 2024-05-08 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_api', '0004_remove_commodity_fk_cmd_group_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='commodity',
            name='fk_cmd_group_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='master_api.commoditygroup'),
            preserve_default=False,
        ),
    ]
