# Generated by Django 4.2.11 on 2024-05-08 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_api', '0005_commodity_fk_cmd_group_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commoditygroup',
            old_name='cmd_discipline_name',
            new_name='cmd_discpln_name',
        ),
        migrations.CreateModel(
            name='Basis',
            fields=[
                ('basis_id', models.AutoField(primary_key=True, serialize=False)),
                ('basis_code', models.CharField(max_length=10, unique=True)),
                ('basis_name', models.CharField(max_length=255, unique=True)),
                ('basis_created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('basis_updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('basis_created_by', models.CharField(blank=True, max_length=255, null=True)),
                ('basis_updated_by', models.CharField(blank=True, max_length=255, null=True)),
                ('fk_tenant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_api.tenantmaster')),
            ],
            options={
                'db_table': 'basis',
            },
        ),
    ]
