# Generated by Django 4.2.11 on 2024-05-08 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_api', '0006_rename_cmd_discipline_name_commoditygroup_cmd_discpln_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameter',
            name='tenant_code',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='standard',
            name='tenant_code',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='tenantmaster',
            name='tenant_code',
            field=models.CharField(max_length=10),
        ),
    ]
