# Generated by Django 4.2.11 on 2024-05-08 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_api', '0007_alter_parameter_tenant_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommoditySpecs',
            fields=[
                ('cs_id', models.AutoField(primary_key=True, serialize=False)),
                ('tenant_code', models.CharField(max_length=10)),
                ('fk_basis_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_api.basis')),
                ('fk_cmd_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_api.commodity')),
                ('fk_parameter_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_api.parameter')),
                ('fk_std_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_api.standard')),
                ('fk_tenant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_api.tenantmaster')),
            ],
            options={
                'db_table': 'commodity_specs',
            },
        ),
    ]
