# Generated by Django 4.2.11 on 2024-05-10 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_api', '0008_commodityspecs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='branch',
            old_name='br_comp_id',
            new_name='fk_compid',
        ),
        migrations.AddField(
            model_name='branch',
            name='br_created_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='br_updated_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='cmp_code',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='branch',
            name='fk_tenant_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='master_api.tenantmaster'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='branch',
            name='tenant_code',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='cmp_compliance_authority',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='cmp_created_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='cmp_seal',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='cmp_stamp',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='cmp_updated_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='fk_tenant_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='master_api.tenantmaster'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='tenant_code',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='company',
            name='cmp_code',
            field=models.CharField(max_length=10),
        ),
    ]
