# Generated by Django 4.2.11 on 2024-05-10 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_api', '0009_rename_br_comp_id_branch_fk_compid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basis',
            name='basis_code',
            field=models.CharField(max_length=225, unique=True),
        ),
    ]
