# Generated by Django 4.2.11 on 2024-05-10 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_api', '0010_alter_basis_basis_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='cmp_cin_no',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='company',
            name='cmp_gst_no',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='company',
            name='cmp_iec_no',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='company',
            name='cmp_pan_no',
            field=models.CharField(max_length=255),
        ),
    ]
